---
backend:
  branch: main
  collections:
    - files:
        - editor:
            preview: true
          fields:
            - label: Titel
              name: title
              widget: string
          file: content/english/team/_index.md
          label: Team
          name: team
  name: git-gateway
media_folder: static/images
public_folder: static/images