---
backend:
  branch: main
  name: git-gateway
collections:
  - files:
      - editor:
          preview: true
        fields:
          - label: Titel
            name: title
            widget: string
          - label: BG_Image
            name: bg_image
            widget: image
          - label: Description
            name: description
            widget: string
          - label: Images
            name: images
            widget: list
            fields:
              - { label: URL, name: path, widget: image}
              - { label: Website-URL, name: url, widget: string}
        file: content/english/references/_index.md
        label: Referenzen
        name: references
      - editor:
          preview: true
        fields:
          - label: Titel
            name: title
            widget: string
          - label: BG_Image
            name: bg_image
            widget: image
          - label: Description
            name: description
            widget: string
          - label: Seitentext
            name: body
            widget: markdown          
        file: content/english/imprint/_index.md
        label: Impressum
        name: imprint
    label: Seitenübersicht
    name: pages
media_folder: static/images
public_folder: /images